{
 "title": "System",
 "description": "System Metrics",
 "tags": [ "system" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM disk WITH KEY = \"path\""
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "SHOW TAG VALUES FROM net WITH KEY = \"interface\""
   }
  ]
 },
 "panels": [
  { "title": "Current Time", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  { "title": "CPU / Mem - $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "node" },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "One Minute Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Five Minute Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Fifteen Minute Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Buffered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "SoftIRQ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "Steal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "Iowait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "Idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "Guest",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "Guest Nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  { "title": "CPU / Mem - $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "One Minute Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Five Minute Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Fifteen Minute Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Buffered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "SoftIRQ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "Steal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "Iowait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "Idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "Guest",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "Guest Nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage - $disk",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
     "repeat": "disk",
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$disk$/" }
       ]
      },
      {
       "alias": "Free",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk Usage - $disk",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$disk$/" }
       ]
      },
      {
       "alias": "Free",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage - $disk",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
     "repeat": "disk",
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$disk$/" }
       ]
      },
      {
       "alias": "Free",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk Usage - $disk",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$disk$/" }
       ]
      },
      {
       "alias": "Free",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "Current Established Connections",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Established TCP",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "tcp_currestab" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 33 },
     "repeat": "interface",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 43 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 43 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 43 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 48 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 48 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 48 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 53 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 53 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 53 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 58 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 58 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Established Connections",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Established TCP",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "tcp_currestab" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 33 },
     "repeat": "interface",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 43 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 43 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 43 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 48 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 48 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 48 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 53 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 53 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 53 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 58 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 58 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "Bytes TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}